# Generated by Django 4.2.3 on 2023-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baza',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='baza',
            name='comments',
            field=models.CharField(default='', max_length=50, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='baza',
            name='group',
            field=models.CharField(default='', max_length=30, verbose_name='Группа'),
        ),
    ]
